"""add registro pendiente

Revision ID: 00adee6a9cfb
Revises: 3788bf18963e
Create Date: 2026-04-25 05:04:07.373819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00adee6a9cfb'
down_revision: Union[str, Sequence[str], None] = '3788bf18963e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_pendiente',
    sa.Column('id_registro_pendiente', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flujo', sa.String(length=20), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification_code_digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("flujo IN ('CLIENTE','ADMINISTRADOR')"),
    sa.CheckConstraint("jsonb_typeof(payload_json) = 'object'", name='ck_registro_pendiente_payload_json_obj'),
    sa.PrimaryKeyConstraint('id_registro_pendiente')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_pendiente')
    # ### end Alembic commands ###
