"""add usuario bloqueado hasta

Revision ID: 3788bf18963e
Revises: 8af1d09b1b3b
Create Date: 2026-04-25 04:29:08.449353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3788bf18963e'
down_revision: Union[str, Sequence[str], None] = '8af1d09b1b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'bloqueado_hasta')
    # ### end Alembic commands ###
