"""add spare parts catalog

Revision ID: 622e32c9bbe3
Revises: 4b5c6d7e8f9a
Create Date: 2026-06-11 11:36:12.552845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622e32c9bbe3'
down_revision: Union[str, Sequence[str], None] = '4b5c6d7e8f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taller_repuesto',
    sa.Column('id_taller_repuesto', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('precio_unitario >= 0'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_taller_repuesto'),
    sa.UniqueConstraint('id_taller', 'nombre', name='uq_taller_repuesto_nombre')
    )
    op.add_column('servicio_repuesto', sa.Column('id_taller_repuesto', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'servicio_repuesto', 'taller_repuesto', ['id_taller_repuesto'], ['id_taller_repuesto'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicio_repuesto', type_='foreignkey')
    op.drop_column('servicio_repuesto', 'id_taller_repuesto')
    op.drop_table('taller_repuesto')
    # ### end Alembic commands ###
