"""initial_schema

Revision ID: 8af1d09b1b3b
Revises: 
Create Date: 2026-04-25 03:20:58.126249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8af1d09b1b3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id_color', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id_color'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('especialidad',
    sa.Column('id_especialidad', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel_complejidad', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('nivel_complejidad BETWEEN 1 AND 5'),
    sa.PrimaryKeyConstraint('id_especialidad'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('marca',
    sa.Column('id_marca', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id_marca'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('metodo_pago',
    sa.Column('id_metodo', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id_metodo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('persona',
    sa.Column('id_persona', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id_persona'),
    sa.UniqueConstraint('ci')
    )
    op.create_table('taller',
    sa.Column('id_taller', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre_comercial', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('radio_accion_km', sa.Numeric(precision=6, scale=2), server_default=sa.text('10.00'), nullable=False),
    sa.Column('reputacion_prom', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('acepta_seguro_propio', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('total_expirados', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_aceptados', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('radio_accion_km > 0'),
    sa.CheckConstraint('reputacion_prom IS NULL OR (reputacion_prom >= 0 AND reputacion_prom <= 5)'),
    sa.CheckConstraint('total_aceptados >= 0'),
    sa.CheckConstraint('total_expirados >= 0'),
    sa.PrimaryKeyConstraint('id_taller')
    )
    op.create_table('tipo_cobertura',
    sa.Column('id_cobertura', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion_plan', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id_cobertura'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('administrador',
    sa.Column('id_persona', sa.BigInteger(), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('catalogo_servicio_taller',
    sa.Column('id_catalogo_servicio', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('id_especialidad', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_base_min', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_base_max', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('incluye_repuestos_basicos', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('precio_base_max >= 0'),
    sa.CheckConstraint('precio_base_max >= precio_base_min', name='ck_catalogo_rango_precio'),
    sa.CheckConstraint('precio_base_min >= 0'),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id_especialidad'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_catalogo_servicio'),
    sa.UniqueConstraint('id_taller', 'nombre', name='uq_catalogo_taller_nombre')
    )
    op.create_table('cliente',
    sa.Column('id_persona', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('cobertura_especialidad',
    sa.Column('id_cobertura', sa.BigInteger(), nullable=False),
    sa.Column('id_especialidad', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['id_cobertura'], ['tipo_cobertura.id_cobertura'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id_especialidad'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cobertura', 'id_especialidad')
    )
    op.create_table('modelo',
    sa.Column('id_modelo', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_marca', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['id_marca'], ['marca.id_marca'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_modelo'),
    sa.UniqueConstraint('id_marca', 'nombre', name='uq_modelo_por_marca')
    )
    op.create_table('operario',
    sa.Column('id_persona', sa.BigInteger(), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('estado_disponibilidad', sa.String(length=20), server_default=sa.text("'DISPONIBLE'"), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('latitud_actual', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitud_actual', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('ultima_ubicacion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("estado_disponibilidad IN ('DISPONIBLE','EN_SERVICIO','NO_DISPONIBLE','BAJA')"),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('taller_especialidad',
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('id_especialidad', sa.BigInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id_especialidad'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_taller', 'id_especialidad')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_persona', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('intentos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bloqueado', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('reputacion_prom', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("tipo_usuario IN ('CLIENTE','OPERARIO','ADMINISTRADOR','SUPER_ADMIN')"),
    sa.CheckConstraint('intentos >= 0'),
    sa.CheckConstraint('reputacion_prom IS NULL OR (reputacion_prom >= 0 AND reputacion_prom <= 5)'),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('id_persona')
    )
    op.create_index('uq_usuario_email_lower', 'usuario', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('dispositivo_usuario',
    sa.Column('id_dispositivo', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('plataforma', sa.String(length=20), nullable=False),
    sa.Column('token_push', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('ultimo_registro', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("plataforma IN ('ANDROID','IOS','WEB')"),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_dispositivo'),
    sa.UniqueConstraint('token_push')
    )
    op.create_table('operario_especialidad',
    sa.Column('id_persona', sa.BigInteger(), nullable=False),
    sa.Column('id_especialidad', sa.BigInteger(), nullable=False),
    sa.Column('anios_experiencia', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('certificacion_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('anios_experiencia >= 0'),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id_especialidad'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_persona'], ['operario.id_persona'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_persona', 'id_especialidad')
    )
    op.create_table('seguro',
    sa.Column('id_seguro', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.BigInteger(), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('id_cobertura', sa.BigInteger(), nullable=False),
    sa.Column('numero_poliza', sa.String(length=50), nullable=True),
    sa.Column('monto_maximo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name='ck_seguro_fechas'),
    sa.CheckConstraint('monto_maximo IS NULL OR monto_maximo >= 0'),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_persona'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_cobertura'], ['tipo_cobertura.id_cobertura'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_seguro')
    )
    op.create_table('vehiculo',
    sa.Column('id_vehiculo', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=15), nullable=False),
    sa.Column('id_modelo', sa.BigInteger(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('id_color', sa.BigInteger(), nullable=False),
    sa.Column('id_persona', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('anio BETWEEN 1900 AND 2100'),
    sa.ForeignKeyConstraint(['id_color'], ['color.id_color'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelo.id_modelo'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_persona'], ['cliente.id_persona'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_vehiculo'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('incidente',
    sa.Column('id_incidente', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('descripcion_cliente', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'REPORTADO'"), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=True),
    sa.Column('id_cliente', sa.BigInteger(), nullable=False),
    sa.Column('id_vehiculo', sa.BigInteger(), nullable=False),
    sa.Column('id_especialidad_reportada_cliente', sa.BigInteger(), nullable=False),
    sa.Column('id_especialidad_detectada', sa.BigInteger(), nullable=True),
    sa.Column('diagnostico_ia_resumen', sa.Text(), nullable=True),
    sa.Column('diagnostico_ia_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confianza_ia', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('transcripcion_audio', sa.Text(), nullable=True),
    sa.Column('etiquetas_imagen', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_triaje', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requiere_revision_manual', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("diagnostico_ia_json IS NULL OR jsonb_typeof(diagnostico_ia_json) = 'object'", name='ck_diagnostico_ia_json_obj'),
    sa.CheckConstraint("estado IN (\n                'REPORTADO',\n                'EN_TRIAJE',\n                'DIAGNOSTICADO',\n                'EN_MATCHMAKING',\n                'EN_PROCESO',\n                'FINALIZADO',\n                'CANCELADO'\n            )"),
    sa.CheckConstraint("etiquetas_imagen IS NULL OR jsonb_typeof(etiquetas_imagen) IN ('array','object')", name='ck_etiquetas_imagen_json_arr'),
    sa.CheckConstraint("severidad IS NULL OR severidad IN ('BAJA','MEDIA','ALTA','CRITICA')"),
    sa.CheckConstraint('confianza_ia IS NULL OR (confianza_ia >= 0 AND confianza_ia <= 100)'),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_persona'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_especialidad_detectada'], ['especialidad.id_especialidad'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_especialidad_reportada_cliente'], ['especialidad.id_especialidad'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id_vehiculo'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_incidente')
    )
    op.create_index('ix_incidente_cliente', 'incidente', ['id_cliente'], unique=False)
    op.create_index('ix_incidente_especialidad_detectada', 'incidente', ['id_especialidad_detectada'], unique=False)
    op.create_index('ix_incidente_estado', 'incidente', ['estado'], unique=False)
    op.create_table('solicitud_servicio',
    sa.Column('id_solicitud', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_incidente', sa.BigInteger(), nullable=False),
    sa.Column('id_taller', sa.BigInteger(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('motivo_cierre', sa.String(length=200), nullable=True),
    sa.Column('prioridad_seguro', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('score_proximidad', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('score_reputacion', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('score_total', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ranking_posicion', sa.Integer(), nullable=True),
    sa.Column('intento_numero', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('es_actual', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("estado IN ('PENDIENTE','ACEPTADA','RECHAZADA','EXPIRADA','CANCELADA','DESCARTADA')"),
    sa.CheckConstraint('fecha_expiracion >= fecha_envio', name='ck_solicitud_fechas'),
    sa.CheckConstraint('intento_numero > 0'),
    sa.CheckConstraint('ranking_posicion IS NULL OR ranking_posicion > 0'),
    sa.CheckConstraint('score_proximidad IS NULL OR (score_proximidad >= 0 AND score_proximidad <= 1)'),
    sa.CheckConstraint('score_reputacion IS NULL OR (score_reputacion >= 0 AND score_reputacion <= 1)'),
    sa.CheckConstraint('score_total IS NULL OR (score_total >= 0 AND score_total <= 1)'),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_solicitud'),
    sa.UniqueConstraint('id_incidente', 'id_taller', 'intento_numero', name='uq_solicitud_incidente_taller_intento')
    )
    op.create_index('ix_solicitud_incidente_estado', 'solicitud_servicio', ['id_incidente', 'estado'], unique=False)
    op.create_index('ix_solicitud_taller_estado', 'solicitud_servicio', ['id_taller', 'estado'], unique=False)
    op.create_index('ux_solicitud_incidente_aceptada', 'solicitud_servicio', ['id_incidente'], unique=True, postgresql_where=sa.text("estado = 'ACEPTADA'"))
    op.create_index('ux_solicitud_incidente_actual', 'solicitud_servicio', ['id_incidente'], unique=True, postgresql_where=sa.text("es_actual = TRUE AND estado IN ('PENDIENTE','ACEPTADA')"))
    op.create_table('servicio',
    sa.Column('id_servicio', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_solicitud', sa.BigInteger(), nullable=False),
    sa.Column('id_seguro', sa.BigInteger(), nullable=True),
    sa.Column('id_persona_operario', sa.BigInteger(), nullable=True),
    sa.Column('estado', sa.String(length=40), server_default=sa.text("'EN_ESPERA_ASIGNACION'"), nullable=False),
    sa.Column('codigo_precotizacion', sa.String(length=50), nullable=True),
    sa.Column('monto_precotizado_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monto_precotizado_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('costo_mano_obra', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('costo_repuestos', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('costo_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('comprobante', sa.Text(), nullable=True),
    sa.Column('confirmacion_cliente', sa.Boolean(), nullable=True),
    sa.Column('fecha_confirmacion_cliente', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_asignacion_operario', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_llegada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones_cierre', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("estado IN (\n                'EN_ESPERA_ASIGNACION',\n                'ASIGNADO',\n                'EN_CAMINO',\n                'EN_SITIO',\n                'EN_DIAGNOSTICO_FISICO',\n                'EN_REPARACION',\n                'ESPERANDO_REPUESTOS',\n                'COMPLETADO_PENDIENTE_CONFIRMACION',\n                'FINALIZADO_PENDIENTE_PAGO',\n                'PAGADO',\n                'CANCELADO'\n            )"),
    sa.CheckConstraint('costo_mano_obra IS NULL OR costo_mano_obra >= 0'),
    sa.CheckConstraint('costo_repuestos >= 0'),
    sa.CheckConstraint('costo_total IS NULL OR costo_total >= 0'),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio', name='ck_servicio_fechas'),
    sa.CheckConstraint('monto_precotizado_max IS NULL OR monto_precotizado_max >= 0'),
    sa.CheckConstraint('monto_precotizado_min IS NULL OR monto_precotizado_min >= 0'),
    sa.CheckConstraint('monto_precotizado_min IS NULL\n            OR monto_precotizado_max IS NULL\n            OR monto_precotizado_max >= monto_precotizado_min', name='ck_servicio_rango_precotizacion'),
    sa.ForeignKeyConstraint(['id_persona_operario'], ['operario.id_persona'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_seguro'], ['seguro.id_seguro'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud_servicio.id_solicitud'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_servicio'),
    sa.UniqueConstraint('codigo_precotizacion'),
    sa.UniqueConstraint('id_solicitud')
    )
    op.create_index('ix_servicio_estado', 'servicio', ['estado'], unique=False)
    op.create_index('ix_servicio_operario', 'servicio', ['id_persona_operario'], unique=False)
    op.create_table('calificacion',
    sa.Column('id_calificacion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_servicio', sa.BigInteger(), nullable=False),
    sa.Column('id_emisor', sa.BigInteger(), nullable=False),
    sa.Column('id_receptor', sa.BigInteger(), nullable=True),
    sa.Column('id_taller_calif', sa.BigInteger(), nullable=True),
    sa.Column('emisor_tipo', sa.String(length=20), nullable=False),
    sa.Column('receptor_tipo', sa.String(length=20), nullable=False),
    sa.Column('estrellas', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("(receptor_tipo = 'PERSONA' AND id_receptor IS NOT NULL AND id_taller_calif IS NULL)\n            OR\n            (receptor_tipo = 'TALLER' AND id_receptor IS NULL AND id_taller_calif IS NOT NULL)", name='ck_calificacion_destino'),
    sa.CheckConstraint("emisor_tipo IN ('CLIENTE','OPERARIO','ADMINISTRADOR')"),
    sa.CheckConstraint("receptor_tipo IN ('PERSONA','TALLER')"),
    sa.CheckConstraint('estrellas BETWEEN 1 AND 5'),
    sa.ForeignKeyConstraint(['id_emisor'], ['persona.id_persona'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_receptor'], ['persona.id_persona'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_taller_calif'], ['taller.id_taller'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    op.create_index('uq_calificacion_persona', 'calificacion', ['id_servicio', 'id_emisor', 'id_receptor'], unique=True, postgresql_where=sa.text('id_receptor IS NOT NULL'))
    op.create_index('uq_calificacion_taller', 'calificacion', ['id_servicio', 'id_emisor', 'id_taller_calif'], unique=True, postgresql_where=sa.text('id_taller_calif IS NOT NULL'))
    op.create_table('evidencia',
    sa.Column('id_evidencia', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipo_evidencia', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=20), server_default=sa.text("'INCIDENTE'"), nullable=False),
    sa.Column('url_archivo', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id_incidente', sa.BigInteger(), nullable=True),
    sa.Column('id_servicio', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("categoria IN ('INCIDENTE','REPARACION','CIERRE')"),
    sa.CheckConstraint("tipo_evidencia IN ('IMAGEN','AUDIO','VIDEO','DOCUMENTO','OTRO')"),
    sa.CheckConstraint('id_incidente IS NOT NULL OR id_servicio IS NOT NULL', name='ck_evidencia_relacion'),
    sa.CheckConstraint('tamano_bytes IS NULL OR tamano_bytes >= 0'),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_evidencia')
    )
    op.create_index('ix_evidencia_incidente', 'evidencia', ['id_incidente'], unique=False)
    op.create_index('ix_evidencia_servicio', 'evidencia', ['id_servicio'], unique=False)
    op.create_table('notificacion',
    sa.Column('id_notificacion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('id_servicio', sa.BigInteger(), nullable=True),
    sa.Column('id_solicitud', sa.BigInteger(), nullable=True),
    sa.Column('canal', sa.String(length=20), server_default=sa.text("'PUSH'"), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('proveedor', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_lectura', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("canal IN ('PUSH','EMAIL','SMS','WEB')"),
    sa.CheckConstraint("estado IN ('PENDIENTE','ENVIADA','FALLIDA','LEIDA')"),
    sa.CheckConstraint("payload IS NULL OR jsonb_typeof(payload) IN ('object','array')", name='ck_notificacion_payload_json'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud_servicio.id_solicitud'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_index('ix_notificacion_usuario_estado', 'notificacion', ['id_usuario', 'estado'], unique=False)
    op.create_table('pago',
    sa.Column('id_pago', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_servicio', sa.BigInteger(), nullable=False),
    sa.Column('id_metodo', sa.BigInteger(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.CHAR(length=3), server_default=sa.text("'BOB'"), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('referencia_externa', sa.String(length=100), nullable=True),
    sa.Column('token_pago', sa.String(length=150), nullable=True),
    sa.Column('qr_url', sa.Text(), nullable=True),
    sa.Column('payload_pasarela', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comprobante', sa.Text(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('fecha_confirmacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("estado IN ('PENDIENTE','CONFIRMADO','RECHAZADO','ANULADO')"),
    sa.CheckConstraint("payload_pasarela IS NULL OR jsonb_typeof(payload_pasarela) = 'object'", name='ck_pago_payload_json_obj'),
    sa.CheckConstraint('monto >= 0'),
    sa.ForeignKeyConstraint(['id_metodo'], ['metodo_pago.id_metodo'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_pago'),
    sa.UniqueConstraint('id_servicio')
    )
    op.create_index('ix_pago_estado', 'pago', ['estado'], unique=False)
    op.create_table('servicio_informe',
    sa.Column('id_informe', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_servicio', sa.BigInteger(), nullable=False),
    sa.Column('accion_realizada', sa.Text(), nullable=False),
    sa.Column('diagnostico_fisico', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_cierre_url', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_informe'),
    sa.UniqueConstraint('id_servicio')
    )
    op.create_table('servicio_repuesto',
    sa.Column('id_servicio_repuesto', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_servicio', sa.BigInteger(), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), server_default=sa.text('1'), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('evidencia_url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('cantidad > 0'),
    sa.CheckConstraint('costo_unitario >= 0'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_servicio_repuesto')
    )
    op.create_index('ix_servicio_repuesto_servicio', 'servicio_repuesto', ['id_servicio'], unique=False)
    op.create_table('servicio_ubicacion',
    sa.Column('id_ubicacion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_servicio', sa.BigInteger(), nullable=False),
    sa.Column('id_persona_operario', sa.BigInteger(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('precision_metros', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('velocidad_kmh', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['id_persona_operario'], ['operario.id_persona'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_ubicacion')
    )
    op.create_index('ix_servicio_ubicacion_servicio_fecha', 'servicio_ubicacion', ['id_servicio', 'fecha_hora'], unique=False)
    op.create_table('bitacora',
    sa.Column('id_bitacora', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('entidad_principal', sa.String(length=30), nullable=False),
    sa.Column('id_entidad_principal', sa.BigInteger(), nullable=True),
    sa.Column('datos_originales', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('hash_evento', sa.String(length=32), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('id_incidente', sa.BigInteger(), nullable=True),
    sa.Column('id_solicitud', sa.BigInteger(), nullable=True),
    sa.Column('id_servicio', sa.BigInteger(), nullable=True),
    sa.Column('id_pago', sa.BigInteger(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("datos_nuevos IS NULL OR jsonb_typeof(datos_nuevos) IN ('object','array','string','number','boolean','null')", name='ck_bitacora_datos_nuevos_json'),
    sa.CheckConstraint("datos_originales IS NULL OR jsonb_typeof(datos_originales) IN ('object','array','string','number','boolean','null')", name='ck_bitacora_datos_originales_json'),
    sa.CheckConstraint("entidad_principal IN (\n                'INCIDENTE',\n                'SOLICITUD',\n                'SERVICIO',\n                'PAGO',\n                'IA',\n                'NOTIFICACION',\n                'USUARIO',\n                'SISTEMA'\n            )"),
    sa.ForeignKeyConstraint(['id_incidente'], ['incidente.id_incidente'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_pago'], ['pago.id_pago'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud_servicio.id_solicitud'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_bitacora')
    )
    op.create_index('ix_bitacora_entidad', 'bitacora', ['entidad_principal', 'id_entidad_principal'], unique=False)
    op.create_index('ix_bitacora_fecha', 'bitacora', ['fecha_hora'], unique=False)
    op.create_index('ix_bitacora_incidente', 'bitacora', ['id_incidente'], unique=False)
    op.create_index('ix_bitacora_pago', 'bitacora', ['id_pago'], unique=False)
    op.create_index('ix_bitacora_servicio', 'bitacora', ['id_servicio'], unique=False)
    op.create_index('ix_bitacora_solicitud', 'bitacora', ['id_solicitud'], unique=False)
    # ### end Alembic commands ###
    # SQL que permanece en la capa DB: funciones y triggers.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fn_set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fn_bitacora_set_hash()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.hash_evento := md5(
                concat_ws('|',
                    coalesce(NEW.accion, ''),
                    coalesce(NEW.tipo_evento, ''),
                    coalesce(NEW.entidad_principal, ''),
                    coalesce(NEW.id_entidad_principal::text, ''),
                    coalesce(NEW.id_usuario::text, ''),
                    coalesce(NEW.id_incidente::text, ''),
                    coalesce(NEW.id_solicitud::text, ''),
                    coalesce(NEW.id_servicio::text, ''),
                    coalesce(NEW.id_pago::text, ''),
                    coalesce(NEW.fecha_hora::text, now()::text),
                    coalesce(NEW.datos_originales::text, ''),
                    coalesce(NEW.datos_nuevos::text, '')
                )
            );
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fn_bitacora_block_changes()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'BITACORA es append-only: no se permiten %', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_persona_updated_at
        BEFORE UPDATE ON persona
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_taller_updated_at
        BEFORE UPDATE ON taller
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_usuario_updated_at
        BEFORE UPDATE ON usuario
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_cliente_updated_at
        BEFORE UPDATE ON cliente
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_administrador_updated_at
        BEFORE UPDATE ON administrador
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_operario_updated_at
        BEFORE UPDATE ON operario
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_especialidad_updated_at
        BEFORE UPDATE ON especialidad
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_marca_updated_at
        BEFORE UPDATE ON marca
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_modelo_updated_at
        BEFORE UPDATE ON modelo
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_color_updated_at
        BEFORE UPDATE ON color
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_vehiculo_updated_at
        BEFORE UPDATE ON vehiculo
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_tipo_cobertura_updated_at
        BEFORE UPDATE ON tipo_cobertura
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_seguro_updated_at
        BEFORE UPDATE ON seguro
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_incidente_updated_at
        BEFORE UPDATE ON incidente
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_catalogo_servicio_taller_updated_at
        BEFORE UPDATE ON catalogo_servicio_taller
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_solicitud_servicio_updated_at
        BEFORE UPDATE ON solicitud_servicio
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_servicio_updated_at
        BEFORE UPDATE ON servicio
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_servicio_informe_updated_at
        BEFORE UPDATE ON servicio_informe
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_servicio_repuesto_updated_at
        BEFORE UPDATE ON servicio_repuesto
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_metodo_pago_updated_at
        BEFORE UPDATE ON metodo_pago
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_pago_updated_at
        BEFORE UPDATE ON pago
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        CREATE TRIGGER trg_bitacora_hash
        BEFORE INSERT ON bitacora
        FOR EACH ROW EXECUTE FUNCTION fn_bitacora_set_hash();
        CREATE TRIGGER trg_bitacora_no_update
        BEFORE UPDATE ON bitacora
        FOR EACH ROW EXECUTE FUNCTION fn_bitacora_block_changes();
        CREATE TRIGGER trg_bitacora_no_delete
        BEFORE DELETE ON bitacora
        FOR EACH ROW EXECUTE FUNCTION fn_bitacora_block_changes();
        """
    )
    op.execute(
        """
        INSERT INTO metodo_pago (nombre)
        VALUES
            ('QR'),
            ('EFECTIVO')
        ON CONFLICT (nombre) DO NOTHING;
        """
    )
    op.execute(
        """
        INSERT INTO especialidad (nombre)
        VALUES
            ('MECANICA_GENERAL'),
            ('ELECTRICIDAD'),
            ('GRUA'),
            ('LLANTAS'),
            ('BATERIA'),
            ('DIAGNOSTICO_GENERAL')
        ON CONFLICT (nombre) DO NOTHING;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bitacora_solicitud', table_name='bitacora')
    op.drop_index('ix_bitacora_servicio', table_name='bitacora')
    op.drop_index('ix_bitacora_pago', table_name='bitacora')
    op.drop_index('ix_bitacora_incidente', table_name='bitacora')
    op.drop_index('ix_bitacora_fecha', table_name='bitacora')
    op.drop_index('ix_bitacora_entidad', table_name='bitacora')
    op.drop_table('bitacora')
    op.drop_index('ix_servicio_ubicacion_servicio_fecha', table_name='servicio_ubicacion')
    op.drop_table('servicio_ubicacion')
    op.drop_index('ix_servicio_repuesto_servicio', table_name='servicio_repuesto')
    op.drop_table('servicio_repuesto')
    op.drop_table('servicio_informe')
    op.drop_index('ix_pago_estado', table_name='pago')
    op.drop_table('pago')
    op.drop_index('ix_notificacion_usuario_estado', table_name='notificacion')
    op.drop_table('notificacion')
    op.drop_index('ix_evidencia_servicio', table_name='evidencia')
    op.drop_index('ix_evidencia_incidente', table_name='evidencia')
    op.drop_table('evidencia')
    op.drop_index('uq_calificacion_taller', table_name='calificacion', postgresql_where=sa.text('id_taller_calif IS NOT NULL'))
    op.drop_index('uq_calificacion_persona', table_name='calificacion', postgresql_where=sa.text('id_receptor IS NOT NULL'))
    op.drop_table('calificacion')
    op.drop_index('ix_servicio_operario', table_name='servicio')
    op.drop_index('ix_servicio_estado', table_name='servicio')
    op.drop_table('servicio')
    op.drop_index('ux_solicitud_incidente_actual', table_name='solicitud_servicio', postgresql_where=sa.text("es_actual = TRUE AND estado IN ('PENDIENTE','ACEPTADA')"))
    op.drop_index('ux_solicitud_incidente_aceptada', table_name='solicitud_servicio', postgresql_where=sa.text("estado = 'ACEPTADA'"))
    op.drop_index('ix_solicitud_taller_estado', table_name='solicitud_servicio')
    op.drop_index('ix_solicitud_incidente_estado', table_name='solicitud_servicio')
    op.drop_table('solicitud_servicio')
    op.drop_index('ix_incidente_estado', table_name='incidente')
    op.drop_index('ix_incidente_especialidad_detectada', table_name='incidente')
    op.drop_index('ix_incidente_cliente', table_name='incidente')
    op.drop_table('incidente')
    op.drop_table('vehiculo')
    op.drop_table('seguro')
    op.drop_table('operario_especialidad')
    op.drop_table('dispositivo_usuario')
    op.drop_index('uq_usuario_email_lower', table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('taller_especialidad')
    op.drop_table('operario')
    op.drop_table('modelo')
    op.drop_table('cobertura_especialidad')
    op.drop_table('cliente')
    op.drop_table('catalogo_servicio_taller')
    op.drop_table('administrador')
    op.drop_table('tipo_cobertura')
    op.drop_table('taller')
    op.drop_table('persona')
    op.drop_table('metodo_pago')
    op.drop_table('marca')
    op.drop_table('especialidad')
    op.drop_table('color')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS fn_bitacora_block_changes();")
    op.execute("DROP FUNCTION IF EXISTS fn_bitacora_set_hash();")
    op.execute("DROP FUNCTION IF EXISTS fn_set_updated_at();")
